// src/pages/AISuggestionsPage.jsx
import React, { useState } from "react";
import api from "../lib/api";
import { Sparkles, Plus, Loader2, Bot } from "lucide-react";
import { toast } from "react-hot-toast";

export default function AISuggestionsPage() {
    const [goal, setGoal] = useState("");
    const [suggestions, setSuggestions] = useState([]);
    const [loading, setLoading] = useState(false);

    const handleGetSuggestions = async (e) => {
        e.preventDefault();
        if (!goal.trim()) return;

        setLoading(true);
        try {
            const res = await api.post("/ai/suggest", { goal });
            setSuggestions(res.data.tasks || []);
            if (res.data.tasks?.length === 0) {
                toast("No suggestions found. Try a different goal.");
            }
        } catch (err) {
            console.error(err);
            toast.error("Failed to get suggestions");
        } finally {
            setLoading(false);
        }
    };

    const addTask = async (taskTitle) => {
        try {
            await api.post("/tasks", {
                title: taskTitle,
                description: `Generated by AI for goal: ${goal}`,
                status: "created",
                priority: "medium"
            });
            toast.success("Task added to your board!");
            setSuggestions(prev => prev.filter(t => t !== taskTitle));
        } catch (err) {
            console.error(err);
            toast.error("Failed to add task");
        }
    };

    return (
        <div className="max-w-3xl mx-auto px-4 py-8">
            <div className="text-center mb-10">
                <h1 className="text-3xl font-bold text-gray-900 dark:text-white flex items-center justify-center gap-3">
                    <Sparkles className="text-purple-500" size={32} />
                    AI Task Assistant
                </h1>
                <p className="text-gray-500 dark:text-gray-400 mt-2">
                    Describe your goal, and I'll break it down into actionable tasks.
                </p>
            </div>

            <div className="bg-white dark:bg-neutral-900 p-6 rounded-3xl shadow-sm border border-gray-100 dark:border-neutral-800 mb-8">
                <form onSubmit={handleGetSuggestions} className="flex gap-4">
                    <input
                        type="text"
                        value={goal}
                        onChange={(e) => setGoal(e.target.value)}
                        placeholder="e.g., Learn React in 30 days, Plan a birthday party..."
                        className="flex-1 px-4 py-3 rounded-xl border border-gray-200 dark:border-neutral-700 bg-gray-50 dark:bg-neutral-800 focus:outline-none focus:ring-2 focus:ring-purple-500 dark:text-white"
                        disabled={loading}
                    />
                    <button
                        type="submit"
                        disabled={loading || !goal.trim()}
                        className="px-6 py-3 bg-purple-600 hover:bg-purple-700 text-white rounded-xl font-medium transition-colors disabled:opacity-50 flex items-center gap-2"
                    >
                        {loading ? <Loader2 className="animate-spin" /> : <Bot />}
                        Ask AI
                    </button>
                </form>
            </div>

            {suggestions.length > 0 && (
                <div className="space-y-4 animate-in fade-in slide-in-from-bottom-4 duration-500">
                    <h2 className="text-lg font-semibold text-gray-900 dark:text-white px-2">
                        Suggested Tasks
                    </h2>
                    <div className="grid gap-3">
                        {suggestions.map((task, i) => (
                            <div
                                key={i}
                                className="flex items-center justify-between p-4 bg-white dark:bg-neutral-900 rounded-2xl border border-gray-100 dark:border-neutral-800 hover:shadow-md transition-all group"
                            >
                                <span className="text-gray-700 dark:text-gray-300 font-medium">{task}</span>
                                <button
                                    onClick={() => addTask(task)}
                                    className="p-2 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 rounded-lg hover:bg-blue-100 dark:hover:bg-blue-900/40 transition-colors opacity-0 group-hover:opacity-100"
                                    title="Add to Tasks"
                                >
                                    <Plus size={20} />
                                </button>
                            </div>
                        ))}
                    </div>
                </div>
            )}
        </div>
    );
}
